# Generated by Django 5.1.4 on 2025-01-12 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usat', '0002_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='file',
            field=models.FileField(upload_to='game_files/'),
        ),
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='game_images/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='usat.game')),
            ],
        ),
    ]
