# Generated by Django 5.1.4 on 2025-01-12 15:53

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usat', '0003_rename_created_at_game_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.CreateModel(
            name='AdditionalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='additional_files/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_files_set', to='usat.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='additional_files',
            field=models.ManyToManyField(blank=True, related_name='games', to='usat.additionalfile'),
        ),
    ]
