# Generated by Django 5.1.4 on 2025-01-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usat', '0004_alter_game_description_additionalfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='additional_files',
        ),
        migrations.RemoveField(
            model_name='gameimage',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='pic',
            field=models.FileField(default='default_game_image.png', upload_to='game_images/'),
        ),
        migrations.DeleteModel(
            name='AdditionalFile',
        ),
        migrations.DeleteModel(
            name='GameImage',
        ),
    ]
