# Generated by Django 5.1.4 on 2025-01-16 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usat', '0005_remove_game_additional_files_remove_gameimage_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='game_images/'),
        ),
        migrations.CreateModel(
            name='GamePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='game_images/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='usat.game')),
            ],
        ),
    ]
