# Generated by Django 5.1.4 on 2025-01-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usat', '0009_rename_web_game_game_game_zip_game_extracted_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_zip',
            new_name='web_game',
        ),
        migrations.RemoveField(
            model_name='game',
            name='extracted_path',
        ),
    ]
