# Generated by Django 5.1.4 on 2025-01-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usat', '0010_rename_game_zip_game_web_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='web_game',
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Role-Playing', 'Role-Playing'), ('Simulation', 'Simulation'), ('Strategy', 'Strategy'), ('Sports', 'Sports'), ('Puzzl', 'Puzzl'), ('Racing', 'Racing'), ('Fighting', 'Fighting'), ('Horror', 'Horror'), ('Other', 'Other')], default='Action', max_length=12),
        ),
    ]
