# Generated by Django 5.1.4 on 2025-01-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usat', '0012_game_howto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomModel',
        ),
        migrations.AddField(
            model_name='game',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='game_backgrounds/'),
        ),
        migrations.AddField(
            model_name='game',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='game_banners/'),
        ),
        migrations.AddField(
            model_name='game',
            name='bg_color',
            field=models.CharField(default='#eeeeee', max_length=7),
        ),
        migrations.AddField(
            model_name='game',
            name='font_family',
            field=models.CharField(default='lato', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='font_size',
            field=models.CharField(default='large', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='link_color',
            field=models.CharField(default='#fa5c5c', max_length=7),
        ),
        migrations.AddField(
            model_name='game',
            name='text_color',
            field=models.CharField(default='#222222', max_length=7),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Role-Playing', 'Role-Playing'), ('Simulation', 'Simulation'), ('Strategy', 'Strategy'), ('Sports', 'Sports'), ('Puzzle', 'Puzzle'), ('Racing', 'Racing'), ('Fighting', 'Fighting'), ('Horror', 'Horror'), ('Other', 'Other')], default='Action', max_length=12),
        ),
    ]
